[package]
name = "sea-orm-rocket-starter"
version = "0.1.0"
edition = "2018"

[dependencies]
async-stream = { version = "^0.3" }
async-trait = { version = "0.1" }
futures = { version = "^0.3" }
futures-util = { version = "^0.3" }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", features = [
  "json",
] }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket.git" }
sea-orm = { version = "^0.2.4", features = [
  "macros",
], default-features = false }
serde_json = { version = "^1" }

[features]
default = ["sqlx-postgres"]
sqlx-mysql = ["sea-orm/sqlx-mysql", "rocket_db_pools/sqlx_mysql"]
sqlx-postgres = ["sea-orm/sqlx-postgres", "rocket_db_pools/sqlx_postgres"]
